package frc.team3602.robot.subsystems;

import static edu.wpi.first.units.Units.*;
import static frc.team3602.robot.Constants.*;

import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.mechanisms.swerve.LegacySwerveRequest.ApplyChassisSpeeds;
import com.ctre.phoenix6.mechanisms.swerve.LegacySwerveRequest.FieldCentric;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.ctre.phoenix6.swerve.SwerveRequest.ApplyFieldSpeeds;
import com.ctre.phoenix6.swerve.utility.WheelForceCalculator.Feedforwards;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.kinematics.SwerveModulePosition;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.team3602.robot.LimelightHelpers;
import frc.team3602.robot.Vision;
import frc.team3602.robot.LimelightHelpers.PoseEstimate;
import frc.team3602.robot.Constants.FieldConstants;
import frc.team3602.robot.generated.TunerConstants.TunerSwerveDrivetrain;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {

    private SwerveRequest.ApplyRobotSpeeds autoRobotDrive = new SwerveRequest.ApplyRobotSpeeds(); // Only for autons
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private final SwerveRequest.FieldCentric fcDrive = new SwerveRequest.FieldCentric();
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    public double heading;
    private final ApplyFieldSpeeds autoRequest = new ApplyFieldSpeeds();

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;
    /* Vision */
    public final Vision vision = new Vision();
    // Start in normal-speed mode so the robot is driveable immediately on enable.
    public double turbo = 0.8;
    /* PID Controllers */
    private final PIDController rotationController = new PIDController(.1, 0, 0.001);
    private final PIDController yController = new PIDController(1, 0, 0.001);

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();
    private final SwerveRequest.FieldCentric drive = new SwerveRequest.FieldCentric();

    public ChassisSpeeds getChassisSpeeds() {
        return super.getKinematics().toChassisSpeeds(getState().ModuleStates);
    }

    /*
     * SysId routine for characterizing translation. This is used to find PID gains
     * for the drive motors.
     */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> setControl(m_translationCharacterization.withVolts(output)),
                    null,
                    this));

    /*
     * SysId routine for characterizing steer. This is used to find PID gains for
     * the steer motors.
     */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(7), // Use dynamic voltage of 7 V
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdSteer_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    volts -> setControl(m_steerCharacterization.withVolts(volts)),
                    null,
                    this));

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle
     * HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on
     * importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    /* This is in radians per second², but SysId only supports "volts per second" */
                    Volts.of(Math.PI / 6).per(Second),
                    /* This is in radians per second, but SysId only supports "volts" */
                    Volts.of(Math.PI),
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdRotation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> {
                        /* output is actually radians per second, but SysId only supports "volts" */
                        setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                        /* also log the requested output for SysId */
                        SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
                    },
                    null,
                    this));

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
     * @param modules             Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve
     *                                  drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz
     *                                  on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry
     *                                  calculation
     *                                  in the form [x, y, theta]ᵀ, with units in
     *                                  meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision
     *                                  calculation
     *                                  in the form [x, y, theta]ᵀ, with units in
     *                                  meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            Matrix<N3, N1> odometryStandardDeviation,
            Matrix<N3, N1> visionStandardDeviation,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation,
                modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Returns a command that applies the specified control request to this swerve
     * drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    public Command setNormalSpeed() {
        return runOnce(() -> {
            turbo = 0.8;
        });

    }

    public Command setTurbo() {
        return runOnce(() -> {
            turbo = 1.0;
        });

    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    double rotationSpeed;

    /**
     * Returns a simple Limelight-based rotation command that tries to center the
     * target in view.
     *
     * This helper is a small vision-alignment utility: if the target is visible, we
     * run a PID controller on Limelight TX. If the target is not visible, the
     * method currently returns a small fallback turn command instead of zero.
     */
    // Review note 2026-03-15 10:15:26 -04:00: this method may be unused in the
    // current codebase.
    public double rAlignment() {
        boolean hasTarget = vision.getHasTarget();

        if (!hasTarget) {
            // Preserve the current fallback behavior for "no target seen."
            return 0.3;
        } else {

            // TX is the horizontal Limelight error in degrees.
            double tx = vision.getTX();

            // Positive output means "rotate until the target error approaches 0."
            rotationSpeed = rotationController.calculate(tx, 0);

            // Ignore tiny outputs so the drivetrain does not hunt back and forth
            // because of small camera noise.
            if (Math.abs(rotationSpeed) < 0.5) {
                rotationSpeed = 0;
            }

            return rotationSpeed;
        }
    }

    public Translation2d getTargetPose() {
        Optional<Alliance> allianceOpt = DriverStation.getAlliance();

        // Check if an alliance is present
        if (allianceOpt.isPresent()) {
            Alliance alliance = allianceOpt.get(); // unwrap the Optional

            if (alliance == Alliance.Blue) {
                return FieldConstants.kBlueTowerPosition;
            } else if (alliance == Alliance.Red) {
                return FieldConstants.kRedTowerPosition;
            }
        }

        // Default to the blue-side tower if the alliance is unknown.
        // This keeps distance math deterministic during startup and testing.
        return FieldConstants.kBlueTowerPosition;
    }

    /**
     * Returns the single pose estimate we want the rest of the robot to trust.
     *
     * We deliberately read from the drivetrain's built-in state estimator so vision,
     * autonomous path following, turret aiming, and dashboard displays all agree on
     * where the robot is on the field.
     */
    public Pose2d getEstimatedPose() {
        return getState().Pose;
    }

    /**
     * Estimates the field-relative distance from the turret to the current target.
     *
     * We start with the robot's latest estimated pose, shift forward to the turret's
     * physical mounting location, and then measure from that point to the target.
     * Using the latest estimated pose here means Limelight corrections can improve
     * shooter distance calculations immediately.
     */
    public double getDistanceToTarget() {
        // Step 1:
        // Read the robot's current field pose from the shared drivetrain estimator.
        //
        // This pose includes:
        // - X position on the field
        // - Y position on the field
        // - robot heading
        //
        // We use the estimator's pose instead of raw wheel odometry so Limelight
        // vision corrections can improve shooter distance immediately.
        Pose2d robotPose = getEstimatedPose();

        // Step 2:
        // Look up the field position of the correct tower for the current alliance.
        //
        // This gives us the fixed goal location we want to measure to.
        Translation2d targetPosition = this.getTargetPose();

        // Step 3:
        // Describe where the turret sits relative to the robot center.
        //
        // +X means forward from the robot center.
        // +Y would mean left from the robot center.
        //
        // Right now the turret is modeled as 11.28 inches forward of center and
        // centered left-to-right. If your measured shot distance seems consistently
        // off, these are some of the first numbers to verify on the real robot.
        double turretOffsetX = Units.inchesToMeters(11.28);
        double turretOffsetY = Units.inchesToMeters(0);

        // Build that robot-relative offset as a 2D translation.
        Translation2d turretOffset = new Translation2d(turretOffsetX, turretOffsetY);

        // Step 4:
        // Rotate the turret offset by the robot's current heading.
        //
        // This converts the turret offset from "robot coordinates" into "field
        // coordinates." Without this step, the code would assume the robot is always
        // facing the same direction and the distance would be wrong whenever the
        // robot turns.
        Translation2d rotatedOffset = turretOffset.rotateBy(robotPose.getRotation());

        // Step 5:
        // Add the rotated turret offset to the robot's field position.
        //
        // This gives the turret's actual position on the field, which is a better
        // shooting reference point than using the center of the drivetrain.
        Translation2d turretPosition = robotPose.getTranslation().plus(rotatedOffset);

        // Step 6:
        // Measure the straight-line distance from the turret to the tower target.
        //
        // WPILib pose math works in meters, so this value starts in meters.
        double distanceMeters = turretPosition.getDistance(targetPosition);

        // Step 7:
        // Convert the distance to feet before returning it.
        //
        // The shooter interpolation table is currently tuned in feet, so this method
        // returns feet to match the lookup table in ShooterSubsystem.
        return Units.metersToFeet(distanceMeters);
    }

    private final Field2d field = new Field2d();
    @Override
    public void periodic() {
        // Read fresh gyro values every loop so MegaTag2 can use the latest drivetrain
        // heading information before we ask the Limelights for a pose estimate.
        Pose2d currentEstimatedPose = getEstimatedPose();
        double currentLinearSpeedMetersPerSecond = Math.hypot(
                getState().Speeds.vxMetersPerSecond,
                getState().Speeds.vyMetersPerSecond);
        double currentYawDegreesPerSecond = getPigeon2().getAngularVelocityZWorld().getValueAsDouble();

        // Pass the current drivetrain state to the Limelight pose subsystem.
        // MegaTag2 uses the heading data directly, and the reliability filters use
        // the robot's current pose and speed to reject stale or unreasonable frames.
        Limelight_Pose.getInstance().CollectDriveState(
                currentEstimatedPose,
                currentYawDegreesPerSecond,
                currentLinearSpeedMetersPerSecond);

        var acceptedVisionMeasurements = Limelight_Pose.getInstance().getAcceptedMeasurements();
        if (!acceptedVisionMeasurements.isEmpty()){
            // Feed every accepted Limelight measurement into the drivetrain's built-in
            // estimator. When both cameras have believable data, using both helps
            // pull long-term odometry drift back toward the field more quickly.
            for (var measurement : acceptedVisionMeasurements) {
                addVisionMeasurement(
                    measurement.poseEstimate.pose,
                    measurement.poseEstimate.timestampSeconds,
                    VecBuilder.fill(
                        measurement.xyStdDev,
                        measurement.xyStdDev,
                        measurement.thetaStdDev));
            }

            Limelight_Pose.getInstance().UpdateVisionCorrectionAdded();
        }

        SmartDashboard.putNumber("Robot X", getEstimatedPose().getX());
        SmartDashboard.putNumber("Robot Y", getEstimatedPose().getY());
        SmartDashboard.putNumber("Robot Angle", getEstimatedPose().getRotation().getDegrees());
        SmartDashboard.putNumber("Pigeon Angle", getPigeon2().getYaw().getValueAsDouble());
  
        SmartDashboard.putNumber("Rotation Speed", this.rotationSpeed);
        SmartDashboard.putNumber("my heading", vision.getTX());
        SmartDashboard.putNumber("Pose Distance", this.getDistanceToTarget());
        
        field.setRobotPose(getEstimatedPose());

        SmartDashboard.putData("PoseVisionAbe", field);

        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply
         * it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts
         * mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is
         * disabled.
         * This ensures driving behavior doesn't change until an explicit disable event
         * occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                        allianceColor == Alliance.Red
                                ? kRedAlliancePerspectiveRotation
                                : kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
            });
        }
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision
     *                              camera.
     * @param timestampSeconds      The timestamp of the vision measurement in
     *                              seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters    The pose of the robot as measured by the
     *                                 vision camera.
     * @param timestampSeconds         The timestamp of the vision measurement in
     *                                 seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose
     *                                 measurement
     *                                 in the form [x, y, theta]ᵀ, with units in
     *                                 meters and radians.
     */
    @Override
    public void addVisionMeasurement(
            Pose2d visionRobotPoseMeters,
            double timestampSeconds,
            Matrix<N3, N1> visionMeasurementStdDevs) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds),
                visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is
     *         empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Connects the drivetrain to PathPlanner's AutoBuilder.
     *
     * This tells PathPlanner how to read the robot pose, how to reset the robot at
     * the start of an autonomous routine, how to command chassis motion, and when a
     * path should be mirrored for the red alliance.
     */
    public void configPathplanner() {
        try {
            AutoBuilder.configure(
                    this::getEstimatedPose, // Current robot pose supplier.
                    this::resetPose, // Lets an auto reset odometry to its starting pose.
                    () -> getState().Speeds, // Current robot-relative chassis speeds.
                    (speeds, feedforwards) -> setControl(
                            // Apply the requested robot-relative chassis speeds and
                            // the wheel-force feedforwards computed by PathPlanner.
                            autoRobotDrive.withSpeeds(speeds)
                                    .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                                    .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())),
                    new PPHolonomicDriveController(
                            new PIDConstants(10), // Translation controller gains.
                            new PIDConstants(7)), // Rotation controller gains.
                    RobotConfig.fromGUISettings(), // Robot geometry from the PathPlanner GUI.
                    () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red, // Mirror for red.
                    this); // Drivetrain subsystem requirement.

        } catch (Exception ex) {
            // If PathPlanner config fails, print the existing debug art so students
            // immediately know auto setup did not initialize correctly.
            System.out.println("Pathplanner no be work :( /n ");
            System.out.println("//               Y.                      _   /n");
            System.out.println("//                 YiL                   .```.  /n");
            System.out.println("//                 Yii;                .; .;;`.   /n ");
            System.out.println("//                 YY;ii.           .;`.;;;; :    /n");
            System.out.println("//                 iiYYYYYYiiiii;;;;i` ;;::;;;;    /n");
            System.out.println("//             _.;YYYYYYiiiiiiYYYii  .;;.   ;;; /n");
            System.out.println("//          .YYYYYYYYYYiiYYYYYYYYYYYYii;`  ;;;;   /n ");
            System.out.println("//        .YYYYYYY$$YYiiYY$$$$iiiYYYYYY;.ii;`..   /n");
            System.out.println("//       :YYY$!.  TYiiYY$$$$$YYYYYYYiiYYYYiYYii.    /n");
            System.out.println("//       Y$MM$:   :YYYYYY$!\"``\"4YYYYYiiiYYYYiiYY.    /n");
            System.out.println("//    `. :MM$$b.,dYY$$Yii\" :'   :YYYYllYiiYYYiYY    /n");
            System.out.println("//  .. :`4MM$!YYYYYYYYYii,.__.diii$$YYYYYYYYYYY/n");
            System.out.println("// .,. $b`P`     \"4$$$$$iiiiiiii$$$$YY$$$$$$YiY;/n");
            System.out.println("//    `,.`$:       :$$$$$$$$$YYYYY$$$$$$$$$YYiiYYL/n");
            System.out.println("//     \"`;$$.    .;PPb$`.,.``T$$YY$$$$YYYYYYiiiYYU: /n ");
            System.out.println("//     ;$P$;;: ;;;;i$y$\"!Y$$$b;$$$Y$YY$$YYYiiiYYiYY /n");
            System.out.println("//     $Fi$$ .. ``:iii.`-\":YYYYY$$YY$$$$$YYYiiYiYYY   /n ");
            System.out.println("//     :Y$$rb ````  `..;;i;YYY$YY$$$$$$$YYYYYYYiYY:    /n");
            System.out.println("//      :$$$$$i;;iiiiidYYYYYYYYYY$$$$$$YYYYYYYiiYYYY. /n");
            System.out.println("//       `$$$$$$$YYYYYYYYYYYYY$$$$$$YYYYYYYYiiiYYYYYY   /n ");
            System.out.println("//       .i!$$$$$$YYYYYYYYY$$$$$$YYY$$YYiiiiiiYYYYYYY    /n");
            System.out.println("//      :YYiii$$$$$$$YYYYYYY$$$$YY$$$$YYiiiiiYYYYYYi\"/n");
        }
    }
}
